Repository logistics-delivery/Back-end, pull requests merged in 2025-03, with the labels that each got.

#14 ✨ feat [#10] : product-service init
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/modules.xml
  .idea/modules/eureka/logistics-delivery.eureka.main.iml
  .idea/modules/gateway/logistics-delivery.gateway.main.iml
  gateway/src/main/resources/application.yml
  product-service/build.gradle
  product-service/src/main/java/com/sparta/product/ProductController.java
  product-service/src/main/java/com/sparta/product/ProductServiceApplication.java
  product-service/src/main/resources/application.yml
  product-service/src/test/java/com/sparta/product/ProductServiceApplicationTests.java
  settings.gradle
Labels: ✨ feat

#18 ✨feat [#10] : slack-service init 추가
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/user-service/logistics-delivery.user-service.main.iml
  gateway/src/main/resources/application.yml
  settings.gradle
  slack-service/build.gradle
  slack-service/src/main/java/com/sparta/slackservice/SlackServiceApplication.java
  slack-service/src/main/java/com/sparta/slackservice/presentation/SlackController.java
  slack-service/src/main/resources/application.yml
  slack-service/src/test/java/com/sparta/slackservice/SlackServiceApplicationTests.java
Labels: 💡init

#21 ✨ feat [#15] : payment-service init
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/eureka/logistics-delivery.eureka.main.iml
  .idea/modules/gateway/logistics-delivery.gateway.main.iml
  .idea/modules/payment-service/logistics-delivery.payment-service.main.iml
  .idea/modules/product-service/logistics-delivery.product-service.main.iml
  .idea/modules/slack-service/logistics-delivery.slack-service.main.iml
  gateway/src/main/resources/application.yml
  payment-service/build.gradle
  payment-service/src/main/java/com/sparta/paymentservice/PaymentServiceApplication.java
  payment-service/src/main/java/com/sparta/paymentservice/presentation/PaymentController.java
  payment-service/src/main/resources/application.yml
  payment-service/src/test/java/com/sparta/paymentservice/PaymentServiceApplicationTests.java
  settings.gradle
Labels: ✨ feat, 💡init

#41 ✨ feat[#39] : common 모듈 생성
  .idea/compiler.xml
  .idea/modules.xml
  common-module/build.gradle
  common-module/src/main/java/com/sparta/commonmodule/entity/BaseEntity.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/DeletedDataAccessException.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/DuplicateResourceException.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/GlobalExceptionHandler.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/InternalServerException.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/InvalidParameterException.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/OperationNotAllowedException.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/OwnershipMismatchException.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/ResourceNotFoundException.java
  common-module/src/main/java/com/sparta/commonmodule/entity/exception/UnauthorizedAccessException.java
  settings.gradle
Labels: ✨ feat

#44 ✨ feat [#27] : Company Create 구현
  .idea/modules/company-service/logistics-delivery.company-service.main.iml
  company-service/build.gradle
  company-service/src/main/java/com/sparta/companyservice/CompanyController.java
  company-service/src/main/java/com/sparta/companyservice/CompanyServiceApplication.java
  company-service/src/main/java/com/sparta/companyservice/application/dto/CompanyDto.java
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/model/Company.java
  company-service/src/main/java/com/sparta/companyservice/domain/model/CompanyType.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/domain/service/CompanyDomainService.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/client/HubClient.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/JpaCompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/sparta/companyservice/presentation/request/CompanyRequest.java
  gradlew
Labels: ✨ feat

#45 ✨ feat[#28]: Order Create 구현
  build.gradle
  order-service/src/main/java/com/sparta/orderservice/Ordercontroller.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/OrderRequestDto.java
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/Order.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/OrderItem.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/OrderStatus.java
  order-service/src/main/java/com/sparta/orderservice/domain/repository/OrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/Ordercontroller.java
Labels: ✨ feat

#46 ✨[#34]:user
  .idea/dataSources.xml
  .idea/modules/common-module/logistics-delivery.common-module.main.iml
  .idea/modules/payment-service/logistics-delivery.payment-service.main.iml
  .idea/modules/user-service/logistics-delivery.user-service.main.iml
  api-http/user/user-service.http
  build.gradle
  gateway/build.gradle
  gateway/src/main/java/com/sparta/gateway/JwtAuthenticationFilter.java
  gateway/src/main/resources/application.yml
  user-service/build.gradle
  user-service/docker-compose.yml
  user-service/src/main/java/com/sparta/user/application/dto/UserSigninReqeustDto.java
  user-service/src/main/java/com/sparta/user/application/dto/UserSigninResponseDto.java
  user-service/src/main/java/com/sparta/user/application/dto/UserSignupRequestDto.java
  user-service/src/main/java/com/sparta/user/application/service/AuthService.java
  user-service/src/main/java/com/sparta/user/application/service/UserService.java
  user-service/src/main/java/com/sparta/user/domain/model/User.java
  user-service/src/main/java/com/sparta/user/domain/model/UserRoleEnum.java
  user-service/src/main/java/com/sparta/user/infastructure/configuration/AuthConfig.java
  user-service/src/main/java/com/sparta/user/infastructure/configuration/JwtConfig.java
  user-service/src/main/java/com/sparta/user/infastructure/repository/JpaUserRepository.java
  user-service/src/main/java/com/sparta/user/presentation/UserController.java
  user-service/src/main/resources/application.yml
Labels: ✨ feat

#50 ♻️[#48] : 로그인 리팩토링
  .idea/modules.xml
  .idea/modules/company-service/logistics-delivery.company-service.main.iml
  .idea/modules/product-service/logistics-delivery.product-service.main.iml
  .idea/modules/shipping-service/logistics-delivery.shipping-service.main.iml
  .idea/modules/slack-service/logistics-delivery.slack-service.main.iml
  api-http/user/user-service.http
  user-service/src/main/java/com/sparta/user/presentation/UserController.java
Labels: ♻️ refactor

#51 ✨ feat [#28] Order Read, Update 기능 구현
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/application/dto/OrderResponseDto.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/UpdateOrderRequestDto.java
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/Order.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/Ordercontroller.java
Labels: ✨ feat

#56 ♻️ refactor [#49] : Company의 create 리팩토링
  company-service/src/main/java/com/sparta/companyservice/application/dto/CompanyDto.java
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/model/Company.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/domain/service/CompanyDomainService.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/client/HubClient.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/JpaCompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/sparta/companyservice/presentation/request/CompanyCreateRequest.java
  company-service/src/main/java/com/sparta/companyservice/presentation/request/CompanyRequest.java
  company-service/src/main/java/com/sparta/companyservice/presentation/response/CompanyResponse.java
Labels: 🩹 fix

#58 ✨ feat [#30] : 상품 생성 구현
  common-module/build.gradle
  product-service/build.gradle
  product-service/src/main/java/com/sparta/product/ProductController.java
  product-service/src/main/java/com/sparta/product/application/service/ProductService.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/domain/model/Product.java
  product-service/src/main/java/com/sparta/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/sparta/product/infrastructure/repository/JpaProductRepository.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/main/java/com/sparta/product/presentation/dto/request/CreateProductRequestDto.java
  product-service/src/main/java/com/sparta/product/presentation/dto/response/CreateProductResponseDto.java
  product-service/src/main/resources/application.yml
  product-service/src/test/http/product.http
Labels: ✨ feat

#61 ♻️ refactor [#60] : 회원가입 리팩토링
  build.gradle
  user-service/build.gradle
  user-service/src/main/java/com/sparta/user/application/dto/UserSigninResponseDto.java
  user-service/src/main/java/com/sparta/user/application/service/UserService.java
  user-service/src/main/java/com/sparta/user/domain/model/User.java
  user-service/src/main/java/com/sparta/user/presentation/UserController.java
Labels: ♻️ refactor

#62 ✨ feat [#57] : Company - Read 구현
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/domain/service/CompanyDomainService.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/JpaCompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
Labels: ✨ feat

#65 ✨ feat [#66] : Delete 기능 구현
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/Ordercontroller.java
Labels: ✨ feat

#73 🐛 bugfix 버그 수정 [#70] Eureka & Gateway 서버 실행 시 DataSource 오류 해결
  eureka/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
Labels: 🐛 bugfix

#74 ✨ feat [#63] : Company Create 리팩토링 & Update 구현
  company-service/src/main/java/com/sparta/companyservice/application/dto/CompanyCreateDto.java
  company-service/src/main/java/com/sparta/companyservice/application/dto/CompanyUpdateDto.java
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/model/Company.java
  company-service/src/main/java/com/sparta/companyservice/domain/service/CompanyDomainService.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/sparta/companyservice/presentation/request/CompanyCreateRequest.java
  company-service/src/main/java/com/sparta/companyservice/presentation/request/CompanyUpdateRequest.java
Labels: ✨ feat

#75 ✨ feat [#59] : 상품 조회 구현
  product-service/src/main/java/com/sparta/product/application/service/ProductService.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/main/java/com/sparta/product/presentation/dto/response/ReadProductResponseDto.java
  product-service/src/test/http/product.http
Labels: ✨ feat

#79 ♻️ refactor [#67]: Order entity 리팩토링
  order-service/src/main/java/com/sparta/orderservice/domain/model/Order.java
Labels: ♻️ refactor

#84 ♻️ refactor[#80] : OrderRepository 리팩토링
  order-service/src/main/java/com/sparta/orderservice/domain/repository/OrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/repository/JpaOrderRepository.java
Labels: ♻️ refactor

#85 ✨ feat [#82] : 상품 삭제 구현
  product-service/src/main/java/com/sparta/product/application/dto/DeleteProductServiceRequestDto.java
  product-service/src/main/java/com/sparta/product/application/service/ProductService.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/test/http/product.http
Labels: ✨ feat

#88 ♻️ refactor [#76] Company 수정 기능 리팩토링
  company-service/src/main/java/com/sparta/companyservice/application/dto/CompanyUpdateDto.java
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/model/Company.java
  company-service/src/main/java/com/sparta/companyservice/presentation/request/CompanyUpdateRequest.java
Labels: ♻️ refactor

#93 ✨ feat [#92] : Company 삭제 기능 추가
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/model/Company.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
Labels: ✨ feat

#98 ♻️[#97] : gateway, user 리팩토링
  gateway/build.gradle
  gateway/src/main/java/com/sparta/gateway/JwtAuthenticationFilter.java
  gateway/src/main/java/com/sparta/gateway/config/SecurityConfig.java
  slack-service/src/main/resources/application.yml
  user-service/build.gradle
  user-service/src/main/java/com/sparta/user/infastructure/configuration/JwtConfig.java
Labels: ♻️ refactor

#100 ✨ feat[#42]hub-service
  common-module/build.gradle
  hub-service/build.gradle
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/HubRoutesService.java
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/HubService.java
  hub-service/src/main/java/com/sparta/hubservice/hub/config/JpaConfig.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/model/Hub.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/repository/HubQueryRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/repository/HubRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/persistence/QueryDSLHubRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubController.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubRoutesController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteCreateResponse.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteResponse.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/service/HubRouteService.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/model/HubRoute.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/model/HubRouteCheckpoint.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/persistence/JPAHubRouteRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
  hub-service/src/main/resources/application.yml
  hub-service/src/test/resources/http/hub-route-test.http
  hub-service/src/test/resources/http/hub-service-test.http
Labels: ✨ feat, 🍻 test

#105 ♻️ refactor [#99] : user-service 코드 리팩토링 및 기능추가
  api-http/user/user-service.http
  gateway/build.gradle
  gateway/src/main/java/com/sparta/gateway/JwtAuthenticationFilter.java
  user-service/build.gradle
  user-service/src/main/java/com/sparta/user/application/dto/UserSigninResponseDto.java
  user-service/src/main/java/com/sparta/user/application/dto/request/UserSigninReqeustDto.java
  user-service/src/main/java/com/sparta/user/application/dto/request/UserSignupRequestDto.java
  user-service/src/main/java/com/sparta/user/application/dto/request/UserUpdateRequestDto.java
  user-service/src/main/java/com/sparta/user/application/dto/response/UserInfoResponseDto.java
  user-service/src/main/java/com/sparta/user/application/dto/response/UserSigninResponseDto.java
  user-service/src/main/java/com/sparta/user/application/service/AuthService.java
  user-service/src/main/java/com/sparta/user/application/service/UserService.java
  user-service/src/main/java/com/sparta/user/domain/model/User.java
  user-service/src/main/java/com/sparta/user/domain/repository/UserRepository.java
  user-service/src/main/java/com/sparta/user/infastructure/configuration/UserConfig.java
  user-service/src/main/java/com/sparta/user/infastructure/repository/JpaUserRepository.java
  user-service/src/main/java/com/sparta/user/presentation/UserController.java
Labels: ✨ feat, ♻️ refactor

#106 ✨ feat[#42] hub-service
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/HubService.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteDeleteResponse.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/service/HubRouteService.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/common/HaversineCalculator.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteCheckpointRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/persistence/JPAHubRouteCheckpointRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
Labels: ✨ feat

#102 ♻️[#91] : Order create 기능 리팩토링
  common-module/src/main/java/com/sparta/commonmodule/entity/BaseEntity.java
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/OrderServiceApplication.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/OrderRequestDto.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/OrderResponseDto.java
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/Order.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderController.java
  order-service/src/main/resources/application.yml
  order-service/src/test/http/order.http
Labels: ♻️ refactor

#111 Bug #110
  common-module/src/main/java/com/sparta/commonmodule/entity/BaseEntity.java
  order-service/build.gradle
Labels: 🐛 bugfix

#117 [Common] Swagger 추가
  build.gradle
  common-module/build.gradle
  common-module/src/main/java/com/sparta/commonmodule/config/SwaggerConfig.java
  gateway/build.gradle
  gateway/src/main/java/com/sparta/gateway/JwtAuthenticationFilter.java
  gateway/src/main/java/com/sparta/gateway/config/SecurityConfig.java
  gateway/src/main/resources/application.yml
  product-service/build.gradle
  product-service/src/main/java/com/sparta/product/ProductServiceApplication.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/main/resources/application.yml
Labels: ✨ feat

#113 ✨ feat [#109] : Company 관련 설정 추가
  company-service/build.gradle
  company-service/src/main/java/com/sparta/companyservice/CompanyServiceApplication.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/resources/application.yml
  company-service/src/test/http/company.http
Labels: ✨ feat, 🍻 test

#115 ♻️ refactor [#103] : Order soft delete 리팩토링
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/Order.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderController.java
Labels: ♻️ refactor

#120 ✨ feat[Order] : Order cancel 기능
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/Order.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderController.java
Labels: ✨ feat

#131 ♻️ refactor[#121] : Order-service Swagger 설정
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/OrderServiceApplication.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderController.java
  order-service/src/main/resources/application.yml
Labels: ♻️ refactor

#124 ✨ feat [#122] : 허브 및 업체 FeignClient 구현
  product-service/build.gradle
  product-service/src/main/java/com/sparta/product/ProductServiceApplication.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/infrastructure/client/CompanyClient.java
  product-service/src/main/java/com/sparta/product/infrastructure/client/HubClient.java
Labels: ✨ feat

#133 ✨ feat [#123] : 상품 검색 구현
  payment-service/build.gradle
  product-service/build.gradle
  product-service/src/main/java/com/sparta/product/application/service/ProductService.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/sparta/product/infrastructure/repository/JpaProductRepository.java
  product-service/src/main/java/com/sparta/product/infrastructure/repository/ProductQueryDSLRepository.java
  product-service/src/main/java/com/sparta/product/infrastructure/repository/config/QueryDslConfig.java
  product-service/src/main/java/com/sparta/product/infrastructure/repository/impl/ProductQueryDSLRepositoryImpl.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/main/java/com/sparta/product/presentation/dto/request/SearchProductRequestDto.java
  product-service/src/main/java/com/sparta/product/presentation/dto/response/SearchProductResponseDto.java
  product-service/src/main/resources/application.yml
  product-service/src/test/http/product.http
Labels: ✨ feat

#138 ✨ feat[#42] hub-service
  hub-service/build.gradle
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/HubService.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/model/Hub.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/repository/HubQueryRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/repository/HubRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/persistence/QueryDSLHubRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/DijkstraPathFinder.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/JGraphTPathFinder.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/PathCalculate.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/PathFinder.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteCreateResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteDeleteResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteDetailsResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/serviceDto/PathValueDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/service/HubRouteService.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/common/HaversineCalculator.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/model/HubRoute.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/model/HubRouteCheckpoint.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteCheckpointRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
Labels: ✨ feat, 🩹 fix

#135 ✨ feat [#134] : 공통모듈 AOP 작성
  api-http/user/user-service.http
  common-module/build.gradle
  common-module/src/main/java/com/sparta/commonmodule/aop/AuthorizationAspect.java
  common-module/src/main/java/com/sparta/commonmodule/aop/RoleCheck.java
  company-service/src/main/java/com/sparta/companyservice/CompanyServiceApplication.java
  hub-service/src/main/java/com/sparta/hubservice/HubServiceApplication.java
  order-service/src/main/java/com/sparta/orderservice/OrderServiceApplication.java
  payment-service/src/main/java/com/sparta/paymentservice/PaymentServiceApplication.java
  product-service/src/main/java/com/sparta/product/ProductServiceApplication.java
  shipping-service/src/main/java/com/sparta/shippingservice/ShippingServiceApplication.java
  slack-service/build.gradle
  slack-service/src/main/java/com/sparta/slackservice/SlackServiceApplication.java
  slack-service/src/main/java/com/sparta/slackservice/presentation/SlackController.java
  user-service/src/main/java/com/sparta/user/UserServiceApplication.java
  user-service/src/main/java/com/sparta/user/application/service/AuthService.java
  user-service/src/main/java/com/sparta/user/infastructure/repository/JpaUserRepository.java
Labels: ✨ feat

#142 ✨ feat [#130] slack crud , Swagger
  slack-service/build.gradle
  slack-service/src/main/java/com/sparta/slackservice/SlackServiceApplication.java
  slack-service/src/main/java/com/sparta/slackservice/application/dto/SlackRequestDto.java
  slack-service/src/main/java/com/sparta/slackservice/application/dto/SlackResponseDto.java
  slack-service/src/main/java/com/sparta/slackservice/application/service/SlackService.java
  slack-service/src/main/java/com/sparta/slackservice/application/service/SlackWebhookService.java
  slack-service/src/main/java/com/sparta/slackservice/domain/model/Slack.java
  slack-service/src/main/java/com/sparta/slackservice/domain/repository/SlackRepository.java
  slack-service/src/main/java/com/sparta/slackservice/infastructure/JpaSlackRepository.java
  slack-service/src/main/java/com/sparta/slackservice/presentation/SlackController.java
  slack-service/src/main/resources/application.yml
  user-service/build.gradle
  user-service/docker-compose.yml
Labels: ✨ feat

#147 🩹 fix [#42] hub-service
  .gitignore
  .idea/dataSources.xml
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/service/HubRouteService.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/model/HubRouteCheckpoint.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteCheckpointRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/persistence/JPAHubRouteCheckpointRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/repository/HubRouteCheckpointRepositoryImpl.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
  hub-service/src/test/resources/http/hub-route-service-test.http
  hub-service/src/test/resources/http/hub-route-test.http
  hub-service/src/test/resources/http/hub-service-test.http
Labels: ✨ feat, 🩹 fix, 🙈 gitfix

#146 ✨ feat [#114] : Querydsl 구현
  company-service/build.gradle
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/config/QuerydslConfig.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanySearchCondition.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/client/HubClient.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/client/dto/HubClientDto.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/querydsl/CompanyQueryRepository.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/querydsl/CompanyQueryRepositoryImpl.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/JpaCompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/resources/application.yml
  company-service/src/test/java/com/sparta/companyservice/CompanyQueryRepositoryImplTest.java
Labels: ✨ feat

#150 ✨feat [#149] :ShippingManager Entity 생성 및 업체 배송 담당자 할당
  shipping-service/build.gradle
  shipping-service/src/main/java/com/sparta/shippingmanager/application/dto/response/ShippingManagerResponseDto.java
  shipping-service/src/main/java/com/sparta/shippingmanager/application/service/ShippingManagerService.java
  shipping-service/src/main/java/com/sparta/shippingmanager/domain/model/ManagerType.java
  shipping-service/src/main/java/com/sparta/shippingmanager/domain/model/ShippingManager.java
  shipping-service/src/main/java/com/sparta/shippingmanager/domain/repository/ShippingManagerRepository.java
  shipping-service/src/main/java/com/sparta/shippingmanager/infrastructure/JpaManagerRepository.java
  shipping-service/src/main/java/com/sparta/shippingmanager/presentation/ShippingManagerController.java
  shipping-service/src/main/java/com/sparta/shippingservice/ShippingServiceApplication.java
  shipping-service/src/main/java/com/sparta/shippingservice/application/dto/client/ShippingManagerResponseDto.java
  shipping-service/src/main/java/com/sparta/shippingservice/application/dto/request/CreateShippingRequestDto.java
  shipping-service/src/main/java/com/sparta/shippingservice/application/service/ShippingService.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/client/ShippingManagerClient.java
  shipping-service/src/main/resources/application.yaml
Labels: ✨ feat

#153 ✨ feat [#148] : Product->Company Id 조회 기능 추가
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/sparta/companyservice/infrastructure/repository/JpaCompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
Labels: ✨ feat

#159 ✨ feat[#132] : Order 검색 기능 추가
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/config/QueryDslConfig.java
  order-service/src/main/java/com/sparta/orderservice/domain/model/Order.java
  order-service/src/main/java/com/sparta/orderservice/domain/repository/OrderQueryDSLRepository.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/repository/JpaOrderRepository.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/repository/OrderQueryDSLRepositoryImpl.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderController.java
Labels: ✨ feat

#156 🍻 test [#152] : User 테스트코드 작성
  user-service/build.gradle
  user-service/src/main/java/com/sparta/user/application/service/UserService.java
  user-service/src/main/java/com/sparta/user/domain/model/User.java
  user-service/src/main/java/com/sparta/user/presentation/UserController.java
  user-service/src/test/java/com/sparta/user/presentation/UserControllerTest.java
Labels: 🍻 test

#161 ✨feat [#160] :ShippingManager 단건 조회 구현
  shipping-service/src/main/java/com/sparta/shippingmanager/application/service/ShippingManagerService.java
  shipping-service/src/main/java/com/sparta/shippingmanager/domain/model/ShippingManager.java
  shipping-service/src/main/java/com/sparta/shippingmanager/domain/model/trnas/ShippingManagerSelf.java
  shipping-service/src/main/java/com/sparta/shippingmanager/domain/repository/ShippingManagerRepository.java
  shipping-service/src/main/java/com/sparta/shippingmanager/presentation/ShippingManagerController.java
  shipping-service/src/main/java/com/sparta/shippingservice/ShippingServiceApplication.java
Labels: ✨ feat

#165 ✨ feat [#42]hub-service
  hub-service/build.gradle
  hub-service/src/main/java/com/sparta/hubservice/HubServiceApplication.java
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/HubShippingScanService.java
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/shipping/ShippingService.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/model/HubShippingScanLog.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/repository/HubShippingScanRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/ShippingFeignClient.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/dto/InboundStatusRequestDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/dto/InboundStatusResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/dto/OutboundStatusRequestDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/dto/OutboundStatusResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/persistence/JPAHubShippingScanRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/repository/HubShippingScanRepositoryImpl.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubShippingScanController.java
Labels: ✨ feat, 🔥 del

#167 ♻️ refactor [#154] 코드 리팩토링
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/test/java/com/sparta/companyservice/CompanyQueryRepositoryImplTest.java
Labels: ♻️ refactor

#166 ✨ feat [#123] : 상품 수정(재고 감소) 구현
  product-service/src/main/java/com/sparta/product/application/dto/DecreaseProductQuantityServiceRequestDto.java
  product-service/src/main/java/com/sparta/product/application/service/ProductService.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/domain/model/Product.java
  product-service/src/main/java/com/sparta/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/main/java/com/sparta/product/presentation/dto/request/DecreaseProductQuantityRequestDto.java
  product-service/src/main/java/com/sparta/product/presentation/dto/response/DecreaseProductQuantityResponseDto.java
  product-service/src/test/http/product.http
Labels: ✨ feat

#170 ✨ feat [#132} Order 재고 감소 FeignClient
  order-service/build.gradle
  order-service/src/main/java/com/sparta/orderservice/OrderServiceApplication.java
  order-service/src/main/java/com/sparta/orderservice/application/dto/OrderRequestDto.java
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/ProductClient.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/request/DecreaseProductQuantityServiceRequestDto.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/response/DecreaseProductQuantityResponseDto.java
Labels: ✨ feat

#172 ✨ feat [#42] hub-service
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/HubShippingScanService.java
  hub-service/src/main/java/com/sparta/hubservice/hub/application/service/shipping/ShippingService.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/model/HubShippingScanLog.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/ShippingFeignClient.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/dto/InboundStatusResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/dto/OutboundStatusRequestDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub/infrastructure/feignclient/dto/OutboundStatusResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubShippingScanController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/CheckpointResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dto/response/HubRouteDetailsResponseDto.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/service/HubRouteService.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteFeignController.java
  hub-service/src/main/resources/application.yml
Labels: ✨ feat, 🩹 fix

#175 ✨ feat [#168] : AuditorAwareImpl 구현 및 @SQLRestriction 설정
  common-module/src/main/java/com/sparta/commonmodule/config/JpaAuditingConfig.java
  common-module/src/main/java/com/sparta/commonmodule/entity/AuditorAwareImpl.java
  common-module/src/main/java/com/sparta/commonmodule/entity/BaseEntity.java
  product-service/src/main/java/com/sparta/product/ProductServiceApplication.java
  product-service/src/main/java/com/sparta/product/domain/model/Product.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/test/http/product.http
Labels: ✨ feat, ♻️ refactor

#181 ✨ feate[#42]hub service
  common-module/src/main/java/com/sparta/commonmodule/config/AuditorAwareImpl.java
  common-module/src/main/java/com/sparta/commonmodule/config/JpaAuditingConfig.java
  common-module/src/main/java/com/sparta/commonmodule/entity/AuditorAwareImpl.java
  common-module/src/main/java/com/sparta/commonmodule/entity/BaseEntity.java
  hub-service/src/main/java/com/sparta/hubservice/hub/domain/model/Hub.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/DijkstraPathFinder.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/JGraphTPathFinder.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/PathCalculate.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/service/HubRouteService.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/model/HubRoute.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteCheckpointRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/persistence/JPAHubRouteCheckpointRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/persistence/JPAHubRouteRepository.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/repository/HubRouteCheckpointRepositoryImpl.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/infrastructure/repository/HubRouteRepositoryImpl.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
  hub-service/src/test/resources/http/create-hub-route-checkpoints.http
  hub-service/src/test/resources/http/create-hub-routes.http
  hub-service/src/test/resources/http/create-hub.http
  hub-service/src/test/resources/http/hub-route-service-test.http
  hub-service/src/test/resources/http/hub-route-total-test.http
  hub-service/src/test/resources/http/hub-service-test.http
  hub-service/src/test/resources/http/hub-total-test.http
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/ShippingClient.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/request/CreateShippingRequestDto.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/response/CreateShippingResponseDto.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/repository/JpaOrderRepository.java
  product-service/src/main/java/com/sparta/product/ProductServiceApplication.java
  product-service/src/main/java/com/sparta/product/domain/model/Product.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/test/http/product.http
Labels: ✨ feat, 🩹 fix

#183 🍻 test[#171] Company 테스트코드 작성
  company-service/build.gradle
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/model/Company.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/test/http/company.http
  company-service/src/test/java/com/sparta/companyservice/application/service/CompanyServiceTest.java
  company-service/src/test/java/com/sparta/companyservice/domain/model/CompanyTest.java
  gateway/src/main/resources/application.yml
Labels: 🍻 test

#184 ♻️ refactor[#182] : User-service 리팩토링
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/ShippingClient.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/request/CreateShippingRequestDto.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/response/CreateShippingResponseDto.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/repository/JpaOrderRepository.java
  user-service/src/main/java/com/sparta/user/UserServiceApplication.java
  user-service/src/main/java/com/sparta/user/application/dto/request/UserSignupRequestDto.java
  user-service/src/main/java/com/sparta/user/application/service/UserService.java
  user-service/src/main/java/com/sparta/user/domain/model/User.java
Labels: ♻️ refactor

#185 ✨ feat [#178] : 상품 증가(원복)
  product-service/src/main/java/com/sparta/product/application/dto/IncreaseProductQuantityServiceRequestDto.java
  product-service/src/main/java/com/sparta/product/application/service/ProductService.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/domain/model/Product.java
  product-service/src/main/java/com/sparta/product/infrastructure/client/CompanyClient.java
  product-service/src/main/java/com/sparta/product/infrastructure/client/HubClient.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/main/java/com/sparta/product/presentation/dto/request/IncreaseProductQuantityRequestDto.java
  product-service/src/main/java/com/sparta/product/presentation/dto/response/IncreaseProductQuantityResponseDto.java
  product-service/src/test/http/product.http
Labels: ✨ feat, ♻️ refactor

#187 🩹 fix[#42] hub service
  docker-compose.yml
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubController.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubShippingScanController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/application/dijkstra/PathCalculate.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
  hub-service/src/main/resources/application.yml
  init.sql
Labels: ✨ feat, 🩹 fix

#189 | ✨ feat [#180] : Order - slack 응답
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/ShippingClient.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/response/CreateShippingResponseDto.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/response/SlackNotificationDto.java
  order-service/src/main/java/com/sparta/orderservice/presentation/controller/OrderController.java
  order-service/src/main/resources/application.yml
Labels: ✨ feat

#188 ♻️ refactor[#182] : User,slack service 리팩토링
  api-http/slack/slack-service.http
  api-http/user/user-service.http
  slack-service/src/main/java/com/sparta/slackservice/presentation/SlackController.java
  slack-service/src/main/resources/application.yml
  user-service/docker-compose.yml
  user-service/src/main/resources/application.yml
Labels: ♻️ refactor

#190 🩹 fix [#186] Company - yml 수정
  company-service/src/main/resources/application.yml
Labels: 🩹 fix

#192 ✨ feat [#42] hub service
  gateway/src/main/resources/application.yml
  hub-service/src/main/java/com/sparta/hubservice/HubServiceApplication.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubController.java
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubShippingScanController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteFeignController.java
  hub-service/src/main/resources/application.yml
Labels: ✨ feat

#193 ♻️ refactor[#191] : AuditorAwareImpl 구현 및 @SQLRestriction 설정
  common-module/src/main/java/com/sparta/commonmodule/config/AuditorAwareImpl.java
  common-module/src/main/java/com/sparta/commonmodule/config/JpaAuditingConfig.java
  common-module/src/main/java/com/sparta/commonmodule/entity/AuditorAwareImpl.java
  common-module/src/main/java/com/sparta/commonmodule/entity/BaseEntity.java
  product-service/src/main/java/com/sparta/product/ProductServiceApplication.java
  product-service/src/main/java/com/sparta/product/domain/model/Product.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
Labels: ♻️ refactor

#197 🩹 fix README
  README.md
Labels: 🩹 fix

#202 ✨ feat[#198] shipping service
  shipping-service/src/main/java/com/sparta/shippingservice/application/service/ShippingHubScanService.java
  shipping-service/src/main/java/com/sparta/shippingservice/domain/model/ShippingHubScanLog.java
  shipping-service/src/main/java/com/sparta/shippingservice/domain/repository/ShippingHubScanLogRepository.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/hub_feign/dto/InboundStatusRequestDto.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/hub_feign/dto/InboundStatusResponseDto.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/hub_feign/dto/OutboundStatusRequestDto.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/hub_feign/dto/OutboundStatusResponseDto.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/repository/JpaShippingHubScanLogRepository.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/repository/ShippingHubScanLogRepositoryImpl.java
  shipping-service/src/main/java/com/sparta/shippingservice/presentation/ShippingHubScanController.java
Labels: ✨ feat

#206 ✨ feat [#195] : 배송로그 서치 기능 구현
  company-service/src/main/java/com/sparta/companyservice/CompanyServiceApplication.java
  shipping-service/build.gradle
  shipping-service/src/main/java/com/sparta/shippingservice/application/dto/request/ShippingRouteSearchCondition.java
  shipping-service/src/main/java/com/sparta/shippingservice/application/service/ShippingService.java
  shipping-service/src/main/java/com/sparta/shippingservice/domain/repository/ShippingRouteQueryRepository.java
  shipping-service/src/main/java/com/sparta/shippingservice/infrastructure/repository/ShippingRouteQueryRepositoryImpl.java
  shipping-service/src/main/java/com/sparta/shippingservice/presentation/ShippingController.java
Labels: ✨ feat

#211 ♻️ refactor[#194] 상품 api 테스트
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/infrastructure/client/CompanyClient.java
  product-service/src/main/java/com/sparta/product/infrastructure/client/HubClient.java
  product-service/src/main/java/com/sparta/product/infrastructure/client/dto/response/HubResponseDto.java
  product-service/src/test/http/product.http
Labels: ✨ feat, ♻️ refactor

#212 🍻 test - Hub test code
  api-http/hub/create-hub-route-checkpoints.http
  api-http/hub/create-hub-routes.http
  api-http/hub/hub-route-total-test.http
  api-http/hub/hub-shipping-feignclient.http
  api-http/hub/hub-total-test.http
  gateway/src/main/resources/application.yml
  hub-service/src/main/java/com/sparta/hubservice/hub/presentation/controller/HubShippingScanController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteController.java
  hub-service/src/main/java/com/sparta/hubservice/hub_route/presentation/controller/HubRouteFeignController.java
  hub-service/src/main/resources/sql/p_hub.sql
  hub-service/src/main/resources/sql/p_hub_route.sql
  hub-service/src/main/resources/sql/p_hub_route_checkpoint.sql
Labels: ♻️ refactor, 🍻 test

#220 ♻️ refactor[#209] 코드 일부 리팩토링
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanySearchCondition.java
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/resources/application.yml
Labels: ♻️ refactor

#225 ♻️ refactor[#222] 주문 -> 상품 FeignClient 수정
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/ProductClient.java
  order-service/src/main/java/com/sparta/orderservice/infrastructure/client/dto/request/DecreaseProductQuantityRequestDto.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
Labels: ✨ feat, ♻️ refactor

#230 💻 README 파일 수정 완료본
  README.md
Labels: 🎨 readme

#232 🩹 fix [#231] 리포지토리 관련 에러 해결
  company-service/src/main/java/com/sparta/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/sparta/companyservice/domain/repository/CompanyRepository.java
Labels: 🐛 bugfix
