Repository logistics-delivery/Back-end, pull requests merged in 2025-04, with the labels that each got.

#239 ✨feat [#238] : stock-service init 추가
  gateway/src/main/resources/application.yml
  settings.gradle
  stock-service/build.gradle
  stock-service/src/main/java/com/sparta/stockservice/StockServiceApplication.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/StockController.java
  stock-service/src/main/resources/application.yml
  stock-service/src/test/java/com/sparta/stockservice/StockServiceApplicationTests.java
Labels: 💡init

#241 ♻️ refactor[#240] : 상품-재고 분리
  api-http/stock/stock.http
  init.sql
  product-service/src/main/java/com/sparta/product/application/dto/DecreaseProductQuantityServiceRequestDto.java
  product-service/src/main/java/com/sparta/product/application/dto/IncreaseProductQuantityServiceRequestDto.java
  product-service/src/main/java/com/sparta/product/application/service/ProductService.java
  product-service/src/main/java/com/sparta/product/application/service/ProductServiceImpl.java
  product-service/src/main/java/com/sparta/product/domain/model/Product.java
  product-service/src/main/java/com/sparta/product/domain/repository/ProductRepository.java
  product-service/src/main/java/com/sparta/product/presentation/ProductController.java
  product-service/src/main/java/com/sparta/product/presentation/dto/request/DecreaseProductQuantityRequestDto.java
  product-service/src/main/java/com/sparta/product/presentation/dto/request/IncreaseProductQuantityRequestDto.java
  product-service/src/main/java/com/sparta/product/presentation/dto/response/DecreaseProductQuantityResponseDto.java
  product-service/src/main/java/com/sparta/product/presentation/dto/response/IncreaseProductQuantityResponseDto.java
  stock-service/src/main/java/com/sparta/stockservice/application/dto/DecreaseStockServiceRequestDto.java
  stock-service/src/main/java/com/sparta/stockservice/application/dto/IncreaseStockServiceRequestDto.java
  stock-service/src/main/java/com/sparta/stockservice/application/service/StockService.java
  stock-service/src/main/java/com/sparta/stockservice/application/service/StockServiceImpl.java
  stock-service/src/main/java/com/sparta/stockservice/domain/model/Stock.java
  stock-service/src/main/java/com/sparta/stockservice/domain/repository/StockRepository.java
  stock-service/src/main/java/com/sparta/stockservice/infrastructure/repository/JpaStockRepository.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/StockController.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/dto/request/CreateStockRequestDto.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/dto/request/DecreaseStockRequestDto.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/dto/request/IncreaseStockRequestDto.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/dto/response/CreateStockResponseDto.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/dto/response/DecreaseStockResponseDto.java
  stock-service/src/main/java/com/sparta/stockservice/presentation/dto/response/IncreaseStockResponseDto.java
Labels: ♻️ refactor

#247 ✨ feat[#203] Slack AI 연동
  .gitignore
  api-http/shipping/shipping-service.http
  company-service/src/main/java/com/sparta/companyservice/presentation/controller/CompanyController.java
  company-service/src/test/http/company.http
  order-service/src/main/java/com/sparta/orderservice/application/service/OrderService.java
  shipping-service/src/main/java/com/sparta/shippingservice/presentation/ShippingController.java
  shipping-service/src/main/resources/application.yaml
  slack-service/build.gradle
  slack-service/src/main/java/com/sparta/slackservice/application/service/SlackService.java
  slack-service/src/main/java/com/sparta/slackservice/domain/repository/SlackRepository.java
  slack-service/src/main/resources/application.yml
Labels: 🩹 fix
